version: '3'

services:
  agent-api:
    build: .
    ports:
      - "3021:3021"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - seorangabi-network

networks:
  default:
    driver: bridge
  seorangabi-network:
    external: true